project_id = "dlspsnjhpmzwxfjajsoa"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[functions]]
name = "normalize-folder-names"
verify_jwt = false

[[functions]]
name = "sync-customers"
verify_jwt = false